### PR TITLE
server: ensure first/last name nullable, make avatar long blob in DB

### LINKED ISSUE #474: User creation requires firstname, lastname
I have recently updated to 0.4.1.

At some point it seems that creating a new user has gone from requiring uid, email, and display name, to also requiring first name and last name.

I can't see any notice of this change, is it intended?

for my own use case first name and last name are not used....I only require username and email from my users. (I am happy to add username as display name as well, as that allows for the possibility to change  at a later date).

It is also not possible to delete firstname or lastname after user creation: 

```
Errors: [updateUser:2:3: Database error: `Execution Error: error returned from database: (code: 1299) NOT NULL constraint failed: users.first_name`]
```

A consequence of this, for my use case, is that I am currently copying the user id into three other settings, in order to create a user (sub-optimal)...and am concerned that the absence of these fields in previously created users will cause other spin off problems (some users are reporting seeing some problems logging into their profile, and I'm concerned that this may be the reason).

### PR DESCRIPTION
**Pull request by nitnelave**
Fixes #474, #486.

### CODE REVIEW

**Comment by pixelrazor** [comment]
Has the schema for mysql, sqlite, and postgres been verified?

File: server/src/domain/sql_migrations.rs [hunk 1]
```diff
@@ -334,6 +334,132 @@ pub async fn upgrade_to_v1(pool: &DbConnection) -> std::result::Result<(), sea_o
...
+    //  - rename the column to a temporary name
+    //  - create the column with the new definition
+    //  - copy the data from the temp column to the new one
+    //  - update the new one if there are changes needed
+    //  - drop the old one
+    let builder = pool.get_database_backend();
+    pool.transaction::<_, (), sea_orm::DbErr>(move |transaction| {
+        Box::pin(async move {
+            #[derive(Iden)]
+            enum TempUsers {
```
Comment (pixelrazor) [inline server/src/domain/sql_migrations.rs:354]: Is this function a general usage function?/ i looks like it is, but this enum is names for the Users table

File: server/src/domain/sql_migrations.rs [hunk 2]
```diff
@@ -334,6 +334,132 @@ pub async fn upgrade_to_v1(pool: &DbConnection) -> std::result::Result<(), sea_o
...
+        ColumnDef::new(Users::LastName).string_len(255).to_owned(),
+        [builder.build(
+            Query::update()
+                .table(Users::Table)
+                .value(Users::LastName, Option::<String>::None)
+                .cond_where(Expr::col(Users::LastName).eq("")),
+        )],
+    )
+    .await?;
+    // Change Avatar from binary to blob(long), because for MySQL this is 65kb.
```
Comment (pixelrazor) [inline server/src/domain/sql_migrations.rs:449]:
```suggestion
    // Change Avatar from binary to blob(long), because for MySQL this is 64kb.
```

File: server/src/domain/sql_migrations.rs (hunk 1 above)
Comment (nitnelave) [reply server/src/domain/sql_migrations.rs:354]: Hmm, the name doesn't actually matter, but you're right that it seems to imply that it does. I'll change that.

File: server/src/domain/sql_migrations.rs (hunk 2 above)
Comment (nitnelave) [reply server/src/domain/sql_migrations.rs]: Thanks!

**Comment by nitnelave** [comment]
> Has the schema for mysql, sqlite, and postgres been verified?

I might have been a bit hasty, but I'm pretty sure it's okay. Would love to be proven wrong, though :) At least the CI tests work, so standing up the server works with all 3 DBs.
